# Generated by Django 4.1 on 2022-08-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0002_mymodel_delete_item_delete_todolist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custom_Sterilization_input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formatedseconds', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
