# Generated by Django 4.1 on 2022-08-28 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0006_placement_delete_publisher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='placement',
        ),
    ]
